"""
Sentiment Analysis Model Module

Handles sentiment classification using fine-tuned or pre-trained transformers models.

Model Options:
1. **Fine-tuned model (recommended)**: ./fine_tuned_distilbert_sentiment
   - Trained on Twitter Entity Sentiment Analysis dataset
   - Better accuracy for chat message analysis
   - Generated by: fine_tune_distilbert.ipynb

2. **Pre-trained model (fallback)**: distilbert-base-uncased-finetuned-sst-2-english
   - General purpose sentiment analysis
   - Auto-used if fine-tuned model not found
"""

import logging
from typing import Dict, List, Tuple, Any
import torch
from transformers import pipeline

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class SentimentAnalyzer:
    """Handles sentiment analysis using fine-tuned DistilBERT model."""
    
    def __init__(self, model_name: str = "./fine_tuned_distilbert_sentiment"):
        """
        Initialize the sentiment analyzer.
        
        Args:
            model_name: Path to fine-tuned model or HuggingFace model identifier
                       Default: local fine-tuned model directory
                       Alternative: "your-username/youtube-sentiment-distilbert" for HuggingFace Hub
        """
        self.model_name = model_name
        self.device = 0 if torch.cuda.is_available() else -1
        self.label_mapping = None
        
        try:
            logger.info(f"Loading model: {model_name}")
            
            # Load the sentiment analysis pipeline
            self.pipeline = pipeline(
                "sentiment-analysis",
                model=model_name,
                device=self.device
            )
            
            logger.info("Model loaded successfully")
            
            # Try to load label mappings if available
            self._load_label_mappings(model_name)
            
        except FileNotFoundError:
            logger.warning(f"Fine-tuned model not found at {model_name}")
            logger.info("Falling back to default pre-trained model...")
            
            # Fallback to pre-trained model
            # self.model_name = "distilbert-base-uncased-finetuned-sst-2-english"
            self.model_name = "Gaben69181/youtube-sentiment-distilbert"
            try:
                self.pipeline = pipeline(
                    "sentiment-analysis",
                    model=self.model_name,
                    device=self.device
                )
                logger.info("Fallback model loaded successfully")
            except Exception as e:
                logger.error(f"Failed to load fallback model: {str(e)}")
                self.pipeline = None
        
        except Exception as e:
            logger.error(f"Failed to load model: {str(e)}")
            self.pipeline = None
    
    def _load_label_mappings(self, model_path: str):
        """
        Try to load label mappings from label_mappings.json.
        
        Args:
            model_path: Path to model directory
        """
        import json
        import os
        
        try:
            label_file = os.path.join(model_path, 'label_mappings.json')
            if os.path.exists(label_file):
                with open(label_file, 'r') as f:
                    self.label_mapping = json.load(f)
                logger.info(f"Label mappings loaded: {self.label_mapping['id2label']}")
        except Exception as e:
            logger.debug(f"Could not load label mappings: {str(e)}")
    
    def classify_sentiment(self, text: str) -> Dict[str, Any]:
        """
        Classify sentiment of a single text.
        
        Args:
            text: Input text to analyze
            
        Returns:
            Dictionary with sentiment classification:
            {
                'label': 'POSITIVE' | 'NEGATIVE' | 'NEUTRAL',
                'score': float (0-1),
                'raw_label': original model label,
                'raw_score': original model score
            }
        """
        if not text or not self.pipeline:
            return {
                'label': 'NEUTRAL',
                'score': 0.5,
                'raw_label': 'UNKNOWN',
                'raw_score': 0.0
            }
        
        try:
            # Get model prediction
            result = self.pipeline(text, truncation=True)[0]
            raw_label = result['label']
            raw_score = result['score']
            
            # Map model output to three-class classification
            sentiment = self._map_sentiment(raw_label, raw_score)
            
            return {
                'label': sentiment,
                'score': raw_score,
                'raw_label': raw_label,
                'raw_score': raw_score
            }
        except Exception as e:
            logger.error(f"Error analyzing text: {str(e)}")
            return {
                'label': 'NEUTRAL',
                'score': 0.5,
                'raw_label': 'ERROR',
                'raw_score': 0.0
            }
    
    @staticmethod
    def _map_sentiment(label: str, score: float) -> str:
        """
        Map model output to three-class sentiment classification.
        
        Args:
            label: Original model label (POSITIVE/NEGATIVE)
            score: Model confidence score (0-1)
            
        Returns:
            Sentiment label: POSITIVE, NEGATIVE, or NEUTRAL
        """
        if label.upper() == 'POSITIVE':
            if score > 0.7:
                return 'POSITIVE'
            else:
                return 'NEUTRAL'
        else:  # NEGATIVE
            if score > 0.7:
                return 'NEGATIVE'
            else:
                return 'NEUTRAL'
    
    def classify_batch(self, texts: List[str]) -> List[Dict[str, Any]]:
        """
        Classify sentiment for multiple texts.
        
        Args:
            texts: List of input texts
            
        Returns:
            List of sentiment classifications
        """
        return [self.classify_sentiment(text) for text in texts]
    
    def get_model_info(self) -> Dict[str, str]:
        """
        Get information about the loaded model.
        
        Returns:
            Dictionary with model information
        """
        return {
            'model': self.model_name,
            'device': 'GPU' if self.device == 0 else 'CPU'
        }
